#      dMMMMMP dMP dMP dMMMMMP dMMMMb dMMMMMMP            
#     dMP     dMP dMP dMP     dMP dMP   dMP               
#    dMMMP   dMP dMP dMMMP   dMP dMP   dMP                
#   dMP      YMvAP" dMP     dMP dMP   dMP                 
#  dMMMMMP    VP"  dMMMMMP dMP dMP   dMP                  
#                                                         
#      dMP dMP .aMMMb  dMMMMb  dMP dMMMMMP .aMMMb  dMMMMb 
#     dMP dMP dMP"dMP dMP.dMP amr   .dMP" dMP"dMP dMP dMP 
#    dMMMMMP dMP dMP dMMMMK" dMP  .dMP"  dMP dMP dMP dMP  
#   dMP dMP dMP.aMP dMP"AMF dMP .dMP"   dMP.aMP dMP dMP   
#  dMP dMP  VMMMP" dMP dMP dMP dMMMMMP  VMMMP" dMP dMP    
#                                                         



# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#0E0F13"

# Main text color
theme[main_fg]="#CBCED0"

# Title color for boxes
theme[title]="#EE64AC"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#26BBD9"

# Background color of selected item in processes box
theme[selected_bg]="#20212B"

# Foreground color of selected item in processes box
theme[selected_fg]="#E3E6EE"

# Color of inactive/disabled text
theme[inactive_fg]="#9DA0A2"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#FAC29A"

# Box outline and divider line color
theme[cpu_box]="#26BBD9"
theme[mem_box]="#29D398"
theme[net_box]="#59E1E3"
theme[proc_box]="#EE64AC"
theme[div_line]="#6F6F70"

# Gradient for all meters and graphs
theme[temp_start]="#FAC29A"
theme[temp_mid]="#E95678"
theme[temp_end]="#EC6A88"


theme[cpu_start]="#59E1E3"
theme[cpu_mid]="#26BBD9"
theme[cpu_end]="#29D398"


theme[free_start]="#26BBD9"
theme[free_mid]="#59E1E3"
theme[free_end]="#6BE4E6"


theme[cached_start]="#FAC29A"
theme[cached_mid]="#F075B5"
theme[cached_end]="#EC6A88"


theme[available_start]="#29D398"
theme[available_mid]="#3FDAA4"
theme[available_end]="#26BBD9"


theme[used_start]="#FAC29A"
theme[used_mid]="#EC6A88"
theme[used_end]="#EE64AC"


theme[download_start]="#59E1E3"
theme[download_mid]="#26BBD9"
theme[download_end]="#29D398"


theme[upload_start]="#FAC29A"
theme[upload_mid]="#EC6A88"
theme[upload_end]="#EE64AC"

#  
#  _______/\\\\\_______/\\\\\\____________/\\\__                                                  
#   _____/\\\///\\\____\////\\\___________\/\\\__                                                 
#    ___/\\\/__\///\\\_____\/\\\___________\/\\\__                                                
#     __/\\\______\//\\\____\/\\\___________\/\\\__                                               
#      _\/\\\_______\/\\\____\/\\\______/\\\\\\\\\__                                              
#       _\//\\\______/\\\_____\/\\\_____/\\\////\\\__                                             
#        __\///\\\__/\\\_______\/\\\____\/\\\__\/\\\__                                            
#         ____\///\\\\\/______/\\\\\\\\\_\//\\\\\\\/\\_                                           
#          ______\/////_______\/////////___\///////\//__                                          
#  ______/\\\\\\\\\\\________________/\\\_______________________/\\\______________________        
#   _____\/////\\\///________________\/\\\______________________\/\\\______________________       
#    _________\/\\\___________________\/\\\______________________\/\\\______________________      
#     _________\/\\\_________/\\\\\____\/\\\____________/\\\\\____\/\\\____________/\\\\\____     
#      _________\/\\\_______/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__    
#       _________\/\\\______/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_   
#        __/\\\___\/\\\_____\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__  
#         _\//\\\\\\\\\_______\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___ 
#          __\/////////__________\/////_____\/////////______\/////_____\/////////______\/////_____
#
