$color = rgba(14, 15, 19, 1)
$inner_color = rgba(14, 15, 19, 0.66)
$outer_color = rgba(238, 100, 172, 1)
$font_color = rgba(203, 206, 208, 1)
$placeholder_color = rgba(157, 160, 162, 0.7)
$check_color = rgba(89, 225, 227, 1)
